import {mergeConfigs} from '../merge-config'
import {dedent} from '../util'

test('merge configs', () => {
  const userVSCodeSettings = dedent(`
    {
      "eslint.packageManager": "yarn",
      // User setting should be preserved
      "eslint.debug": true,
      "files.exclude": {
        // vscode excludes this by default
        "**/.git": false
      },
      "files.watcherExclude": {
        /**
         * If these aren't excluded from watcher tasks it can cause performance issues
         * when trying to load large projects
         */
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/**": true
      }
    }
  `)

  const teamVSCodeSettings = dedent(`
    {
      // Team tooling requires overriding package manager
      "eslint.packageManager": "pnpm",
      "custom.team.plugin": {
        // very important setting that everyone should have
        "activityBarColor": "#ff0000"
      },
      "files.watcherExclude": {
        // ignore file generated by the team's custom code generator
        "**/team-code-generator/generated/**": true
      }
    }
  `)

  const merged = mergeConfigs({
    filepath: '.vscode/settings.json',
    existingContent: userVSCodeSettings,
    targetContent: teamVSCodeSettings,
  })

  expect(merged).toMatchInlineSnapshot(`
    "{
      // Team tooling requires overriding package manager
      \\"eslint.packageManager\\": \\"pnpm\\",
      \\"custom.team.plugin\\": {
        // very important setting that everyone should have
        \\"activityBarColor\\": \\"#ff0000\\"
      },
      \\"files.watcherExclude\\": {
        // ignore file generated by the team's custom code generator
        \\"**/team-code-generator/generated/**\\": true,
        /**
         * If these aren't excluded from watcher tasks it can cause performance issues
         * when trying to load large projects
         */
        \\"**/.git/objects/**\\": true,
        \\"**/.git/subtree-cache/**\\": true,
        \\"**/node_modules/**\\": true
      },
      // User setting should be preserved
      \\"eslint.debug\\": true,
      \\"files.exclude\\": {
        // vscode excludes this by default. it doesn't take much space up though, so enable it
        \\"**/.git\\": false
      }
    }"
  `)
})
